Login practice
blbarr01/EnglishLearningInitiative pull request #13
Opened 2022-10-26 00:13 UTC by PrabhG999

finished log in module demo.

2022-10-26 16:49 UTC, blbarr01 requested changes
these files are ok but they'll need to be converted to typescript components; for now place these two files within a new folder called Login and resubmit for merge

2022-10-26 17:36 UTC, PrabhG999 commented
> 
where should i create the log in folder?

2022-10-26 18:05 UTC, blbarr01 commented
> > 
> 
> where should i create the log in folder?

in the root folder for the project:
EnglishLanguage . . .  
     |-> ELLI 
  ###    |-> Login 
     |->miscfiles.*

2022-11-17 02:03 UTC, blbarr01 approved these changes

2022-11-17 02:03 UTC, merged